apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
    shutdownConfigMap: "shutdown-configmap"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shutdown-configmap
data:
  shutdown.sh: |
    echo "shutdown in progress..."
    master=$(redis-cli -h ${RFS_REDISFAILOVER_SERVICE_HOST} -p ${RFS_REDISFAILOVER_SERVICE_PORT_SENTINEL} --csv SENTINEL get-master-addr-by-name mymaster | tr ',' ' ' | tr -d '\"' |cut -d' ' -f1)
    redis-cli SAVE
    if [[ $master ==  $(hostname -i) ]]; then
      redis-cli -h ${RFS_REDISFAILOVER_SERVICE_HOST} -p ${RFS_REDISFAILOVER_SERVICE_PORT_SENTINEL} SENTINEL failover mymaster
    fi
