apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: redisoperator
  name: redisoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisoperator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: default
      labels:
        app: redisoperator
    spec:
      containers:
      - image: gridson/redis-operator:1.5-tmp
        imagePullPolicy: IfNotPresent
        env:
          - name: REDIS_EXPORTER_IMAGE
            value: "oliver006/redis_exporter"
          - name: REDIS_EXPORTER_IMAGE_VERSION
            value: "v0.11.3"
          - name: REDIS_IMAGE
            value: "redis"
          - name: REDIS_IMAGE_VERSION
            value: "3.2.5"
          - name: APP_LABEL
            value: "redisfailover-test"
        name: app
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      restartPolicy: Always
