// Code generated by mockery v1.0.0
package mocks

import failover "github.com/spotahome/redis-operator/pkg/failover"
import mock "github.com/stretchr/testify/mock"

// RedisFailoverCheck is an autogenerated mock type for the RedisFailoverCheck type
type RedisFailoverCheck struct {
	mock.Mock
}

// Check provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) Check(rFailover *failover.RedisFailover) error {
	ret := _m.Called(rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(*failover.RedisFailover) error); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMaster provides a mock function with given fields: rFailover
func (_m *RedisFailoverCheck) GetMaster(rFailover *failover.RedisFailover) (string, error) {
	ret := _m.Called(rFailover)

	var r0 string
	if rf, ok := ret.Get(0).(func(*failover.RedisFailover) string); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*failover.RedisFailover) error); ok {
		r1 = rf(rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
