// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/spotahome/redis-operator/client/k8s/clientset/versioned/typed/redisfailover/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDatabasesV1 struct {
	*testing.Fake
}

func (c *FakeDatabasesV1) RedisFailovers(namespace string) v1.RedisFailoverInterface {
	return &FakeRedisFailovers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDatabasesV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
