{
 "title": "redis operator details",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "query": {
     "query": "label_values(redis_operator_controller_cluster_ok, name)"
    }
   },
   {
    "name": "kubernetesResource",
    "query": {
     "query": "label_values(redis_operator_controller_ensure_resource{resource_name=\"$tenant\"}, object_name)"
    }
   },
   {
    "name": "kubernetesnamespace",
    "query": {
     "query": "label_values(redis_operator_controller_ensure_resource{resource_name=\"$tenant\"}, object_namespace)"
    }
   },
   {
    "name": "redis_pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=\"StatefulSet\", created_by_name=~\"rfr-$tenant\"}, pod_ip)"
    }
   },
   {
    "name": "sentinel_pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{ created_by_kind=\"ReplicaSet\", created_by_name=~\"rfs-$tenant-[0-9a-z]{10}\"}, pod_ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$tenant - operator functioning health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (namespace, name) (redis_operator_controller_cluster_ok{name=\"$tenant\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "$tenant sentinel health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(redis_operator_controller_sentinel_check{resource=\"$tenant\", status=\"UNHEALTHY\"}[30s]) * 30)\n",
     "legendFormat": "Sentinel Status"
    }
   ]
  },
  {
   "title": "$tenant redis health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(redis_operator_controller_redis_check{resource=\"$tenant\", status=\"UNHEALTHY\"}[30s]) * 30)\n",
     "legendFormat": "Sentinel Status"
    }
   ]
  },
  {
   "title": "Total redis pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{created_by_kind=\"StatefulSet\", created_by_name=~\"rfr-$tenant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sentinel pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{created_by_kind=\"ReplicaSet\", created_by_name=~\"rfs-$tenant-[0-9a-z]+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total redis API calls made in last minute (aggregated)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (rate(redis_operator_controller_redis_operations{IP=~\"$redis_pod_ip|$sentinel_pod_ip\"}[1m]) * 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total K8s API calls made in last minute (aggregated)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(redis_operator_controller_k8s_operations{namespace=\"$kubernetesnamespace\", object=~\"$kubernetesResource\"}[1m]) * 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operator - Functioning Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Sentinel Checks - Unhealthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": " (rate(redis_operator_controller_sentinel_check{resource=\"$tenant\", status=\"UNHEALTHY\"}[60s]) * 60) > bool 0",
     "legendFormat": "{{indicator}} {{instance}}"
    }
   ]
  },
  {
   "title": "Redis Checks - Unhealthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": " (rate(redis_operator_controller_redis_check{resource=\"$tenant\", status=\"UNHEALTHY\"}[60s]) * 60) > bool 0",
     "legendFormat": "{{indicator}} {{instance}}"
    }
   ]
  },
  {
   "title": "Sentinel Checks - Healthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "min by (indicator, instance) (rate(redis_operator_controller_sentinel_check{resource=\"$tenant\", status=\"HEALTHY\"}[60s]) * 60) != bool 0",
     "legendFormat": "{{indicator}}"
    }
   ]
  },
  {
   "title": "Redis Checks - Healthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "min by (indicator, instance) (rate(redis_operator_controller_redis_check{resource=\"$tenant\", status=\"HEALTHY\"}[60s]) * 60) != bool 0",
     "legendFormat": "{{indicator}}"
    }
   ]
  },
  {
   "title": "k8s ops - failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (namespace, kind, object, operation) (rate(redis_operator_controller_k8s_operations{namespace=\"$kubernetesnamespace\", object=~\"$kubernetesResource\",status=\"FAIL\"}[1m]) * 30)",
     "legendFormat": "{{namespace}} {{kind}} {{object}} {{operation}} {{status}}"
    }
   ]
  },
  {
   "title": "redis ops - failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (namespace, kind, operation, status, IP) (rate(redis_operator_controller_redis_operations{IP=~\"$redis_pod_ip|$sentinel_pod_ip\",status=\"FAIL\"}[1m]) * 30)",
     "legendFormat": "{{namespace}} {{kind}} {{IP}} {{operation}} {{status}} "
    }
   ]
  },
  {
   "title": "k8s ops - all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(redis_operator_controller_k8s_operations{namespace=\"$kubernetesnamespace\", object=~\"$kubernetesResource\"}[1m]) * 30",
     "legendFormat": "{{namespace}} {{kind}} {{object}} {{operation}} {{status}}"
    }
   ]
  },
  {
   "title": "redis ops - all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (namespace, kind, operation, status, IP) (rate(redis_operator_controller_redis_operations{IP=~\"$redis_pod_ip|$sentinel_pod_ip\"}[1m]) * 30)",
     "legendFormat": "{{namespace}} {{kind}} {{IP}} {{operation}} {{status}} "
    }
   ]
  },
  { "title": "Go Metrics system metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "rate of objects allocated [heap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "(rate(go_memstats_mallocs_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "number of live objects [heap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"} -  go_memstats_frees_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "heap memory in use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "stack memory allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(rate(go_memstats_alloc_bytes_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "stack memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "number of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration [max]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\", quantile=\"1\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU throttled [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod, container) ((container_cpu_cfs_throttled_periods_total{container=\"app\", pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"} / container_cpu_cfs_periods_total{container=\"app\", pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"} ) * 100)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}